### PR TITLE
add src

### PR DESCRIPTION
**Pull request by daniel-malka**

### CODE REVIEW

**Comment by FiLLa-FaS** [comment]
Hey! Thanks for the sending your project for review - you already have done a lot of work! You still need to fix some issues, I hope that my comment will help you to improve your project and get more points. Good luck!✨

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
    * You should check all text properties of all text elements on all screen resolutions (including correct `font-family`)
    * You need to check and fix all spaces between elements, components and containers. All spaces should match the mockup for all breakpoints screen resolutions
    * Active header tab bottom line should be placed in header bottom line https://disk.yandex.ru/i/QHxBLV4VoBZxeg
    * Incorrect background color of the footer on the main page
    * Footer section shouldn't be sticky or fixed
    * Preloader component doesn't match the mockup
    * News card shouldn't have border
    * `NewsCard-img` shouldn't have bottom rounded corners
    * Incorrect height of the `article.NewsCard` on all breakpoints
    * Mobile navigation is broken on 565px+ screen resolutions
    * You should add more button after the news cards on the project
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * The page scrolls horizontally on 973px - 1042px screen resolutions
    * All page content should be centered horizontally on intermediate screen resolutions
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * Header active tab should be marked with modifier instead of BEM element `header__active-white`
    * Please don't use capital letters for class names
    * Content of news card uses many BEM block classes, it's not what BEM methodology about, please use BEM element classes for content that shouldn't be reused
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.
    * You need to fix all linting warnings of the project

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * `search__input-button` should have pointer cursor and correct hover and clicked state
    * book and trash icon of the news card should have correct hover and marked states
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
    * All icons should be in `svg` format
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [ ]  Images have an `alt` attribute containing appropriate values.
    * `navFirst` and `navSecond` doesn't have alt
- [x]  Raster and vector images have been optimized.

## Number of points: 60

**Comment by daniel-malka** [comment]
hi changed a lot...(=

**Comment by FiLLa-FaS** [comment]
Hey! Thanks for the corrections, many issues were fixed and the project looks much better! Several small issues are marked below, I hope they help you to improve your project and get more points. Good luck!✨

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
    * Header `selected` tab line width bigger than it should be according to the mockup https://disk.yandex.ru/i/ybFbJb1XEab_hw
    * Incorrect distance between `search__title` and `search__pargraph`, `search__pargraph` and `search__input` on 768, 320 viewports
    * Big distance between `about` and `footer` sections on 768 viewport
    * Big distance between logo part and the first link in nav menu and between sign in button and the end of the nav menu on 320 viewport https://disk.yandex.ru/i/MjKiGUTQz0QmGw https://disk.yandex.ru/i/6wOMFPi3f_alMg
    * Incorrect text properties of `search__input-button` on 320 viewport
    * Incorrect text properties of the `about__paragraph` on 320 viewport
    * Incorrect distance between `practicum` and `home` footer links on 320 viewport
    *  Incorrect size of the `newsCardList__cards-listItem` on 1440 viewport
    * You should add more button after the news cards on the project https://disk.yandex.ru/i/adwwlQgeqEGIOw
    * Incorrect background color of the footer section on ``saved-news` page
    * `saved-news` page should have 3 cards in a row on 768px and 1440px screen resolutions
    * Incorrect font is rendered for `newsCard-text-date` item
    * Big distance between `newsCardList-container` and footer on 768 viewport
    * `header__navburger` icon should be black on `saved-news` page
    * `header__wrap` should have black background and white logo when the nav menu os opened on `saved-news` page  https://disk.yandex.ru/d/9_cP0CNrLH3kOg
    * You need to check all spaces and text properties for all elements inside `savednews__text` item on 320 viewport
    * Incorrect height of the popup window on 320 viewport
    * Incorrect width of the popup content on 320 viewport
    * `not-found` block should be centered horizontally https://disk.yandex.ru/i/qZjn_JB9B3qizg
- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * The main page scrolls horizontally on 901px - 912px screen resolutions and `saved-news` page scrolls on 501px - 590px screen resolutions
    * `about` section content should be centered horizontally on intermediate screen resolutions, side spaces should be equal to eeach other
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * Header active tab should be marked with modifier instead of BEM element `header__active-white`
    * Please don't use capital letters for class names
    * Content of news card uses many BEM block classes, it's not what BEM methodology about, please use BEM element classes for content that shouldn't be reused
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.
    * You should fix all eslint errors https://disk.yandex.ru/i/gBmg23fhDQp3HQ

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * `search__input-button` should have pointer cursor and correct hover and clicked state
    * book and trash icon of the news card should have correct hover and marked states
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
    * `navFirst` and `navSecond` doesn't have `alt`
- [x]  Raster and vector images have been optimized.

## Number of points: 62

**Comment by daniel-malka** [comment]
tried very hard to fix nav menu on 320vp. friend told me that i should use useLayoutEffect to solve the issue. but dont know how..
i will try to solve it.
must finish the project by tomorrow evening...

**Comment by FiLLa-FaS** [comment]
Hey! You've got more than 80 points, so your project has been accepted! You still can fix the rest issues and improve your project, but now you can move on to the next stage. Good luck!🚀

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
    * Header selected tab line width bigger than it should be according to the mockup https://disk.yandex.ru/i/LUtZQUuAI3KiFw
    * Incorrect distance between `search__title` and `search__pargraph`, `search__pargraph` and `search__input` on 768, 320 viewports
    * `not-found` content should be centered on 320 viewport
    * You need to check all spaces and text properties for all elements inside `savednews__text` item on 320 viewport
    * `header__logo` and `header__navburger` should be white with dark background on saved-news page
    * Incorrect width of `newscardlist__button` on 320 viewport
    * Incorrect height of the popup window on 320 viewport
    * Incorrect width of `popup__input` on 320 viewport
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * You can't use BEM `ul__li-active-dark` element class outside of its block
    * Please use BEM elements classes for `newscard` content items, it has too much BEM blocks, but all these entities are used only inside card, so you don't need to make them a BEM block
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * `search__input-button` should have correct hover and clicked state according to the mockup https://disk.yandex.ru/i/b4U21KyHwPrV_w
    * book and trash icon of the news card should have correct hover and marked states
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 81

**Pull request merged**
